### ISSUE TITLE
"$$".replace('$$','$$') = '$'

### ISSUE THREAD

**Issue by yelloxing** [etcpack/etcpack#3]
![截屏2022-04-21 15 26 08](https://user-images.githubusercontent.com/23074691/164400779-1d40628f-f53b-4453-b9aa-0ffcadeead55.png)

**Comment by yelloxing** [comment]
@nefbl/pack 存在一样的问题，导致如果存在 $$ , 最终变成了$

**Comment by hai2007** [comment]
etcpack从v0.9.0，@nefbl/pack从v0.5.0开始，修复了此问题
